- hosts: localhost
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    # Foundation
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml

    # Look & feel
    - include: tasks/polybar.yml
    - include: tasks/i3.yml

    # Development
    - include: tasks/node.yml
    - include: tasks/neovim.yml
    - include: tasks/oh-my-zsh.yml
    - include: tasks/tmux.yml
    - include: tasks/docker.yml
    - include: tasks/fzf.yml
    - include: tasks/github.yml

    # Misc
    - include: tasks/chrome.yml
    - include: tasks/spotify.yml
    - include: tasks/skype.yml
