- hosts: localhost
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    # Foundation
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/fzf.yml

    # Look & feel
    - include: tasks/polybar.yml
    - include: tasks/i3.yml
    - include: tasks/dwm.yml

    # Development
    - include: tasks/zsh.yml
    - include: tasks/node.yml
    - include: tasks/neovim.yml
    - include: tasks/tmux.yml
    - include: tasks/docker.yml
    - include: tasks/git.yml
    - include: tasks/alacritty.yml

    # Misc
    - include: tasks/chrome.yml
    - include: tasks/spotify.yml
    - include: tasks/skype.yml
