- name: Install system packages
  become: true
  apt: name={{item}}
  with_items:
    - unzip
    - curl
    - blueman
    - xclip
    - clipit
    - fzf
    - zsh
    - ripgrep
  tags:
    - install
    - core
