- name: Docker
  become: true
  tags:
    - install
    - docker
  block:
    - name: Docker - Install dependencies
      ansible.builtin.apt:
        name: '{{item}}'
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Docker - Add apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker - Add apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

    - name: Docker - Install
      ansible.builtin.apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: Docker - Adding {{ lookup('env', 'USER') }} to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Docker - Install docker-compose
      remote_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
