- name: .dotfiles
  tags:
    - install
    - dotfiles
  block:

    - name: .dotfiles - Clone repository
      ansible.builtin.git:
        repo: git@github.com:fenliz/.dotfiles.git
        dest: ~/.dotfiles
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: master

    - name: .dotfiles - Install stow
      become: true
      ansible.builtin.apt: 
        name: stow

    - name: .dotfiles - Stow files
      ansible.builtin.shell: 
        chdir: ~/.dotfiles
        cmd: ./install.sh
