- name: fzf
  tags:
    - install
    - fzf
  block:
    - name: fzf - Clone repository
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        depth: 1
        dest: ~/third_party/fzf

    - name: fzf - Build & install
      shell: cd ~/third_party/fzf && ./install
