- name: Node
  tags:
    - install
    - node
  block:
    - name: Node - Install nvm
      ansible.builtin.shell:
        cmd: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.0/install.sh | bash
        chdir: ~
        creates: ~/.nvm/nvm.sh

    - name: Node - Install node 14.18.1
      ansible.builtin.shell:
        cmd: . ~/.nvm/nvm.sh && nvm install 14.18.1
        chdir: ~
        creates: ~/.nvm/versions/node/v14.18.1"

    - name: Node - Install yarn
      ansible.builtin.shell:
        cmd: . ~/.nvm/nvm.sh && npm install yarn --global
