- name: Polybar
  tags:
    - install
    - polybar
  block:
    - name: Polybar - Install dependecies
      become: true
      ansible.builtin.apt:
        name: '{{item}}'
      with_items:
        - build-essential 
        - git 
        - cmake 
        - cmake-data 
        - pkg-config 
        - python3-sphinx 
        - python3-packaging 
        - libuv1-dev 
        - libcairo2-dev 
        - libxcb1-dev 
        - libxcb-util0-dev 
        - libxcb-randr0-dev 
        - libxcb-composite0-dev 
        - python3-xcbgen 
        - xcb-proto 
        - libxcb-image0-dev 
        - libxcb-ewmh-dev 
        - libxcb-icccm4-dev
        - rofi

    - name: Polybar - Install optional dependecies
      become: true
      ansible.builtin.apt:
        name: '{{item}}'
      with_items:
        - libxcb-xkb-dev 
        - libxcb-xrm-dev 
        - libxcb-cursor-dev 
        - libasound2-dev 
        - libpulse-dev 
        - i3-wm 
        - libjsoncpp-dev 
        - libmpdclient-dev 
        - libcurl4-openssl-dev 
        - libnl-genl-3-dev

    - name: Polybar - Clone repository
      ansible.builtin.git:
        repo: https://github.com/polybar/polybar
        recursive: true
        dest: ~/third_party/polybar

    - name: Polybar - Build & install
      shell: cd ~/third_party/polybar && ./build.sh
