- name: Spotify
  become: true
  tags:
    - install
    - spotify
  block:
    - name: Spotify - Add apt key
      ansible.builtin.apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present

    - name: Spotify - Add apt repository
      ansible.builtin.apt_repository:
        repo: deb http://repository.spotify.com stable non-free

    - name: Spotify - Install
      ansible.builtin.apt:
        name: spotify-client
        update_cache: yes
        state: latest
